-- liquibase formatted sql

-- changeset salikhdev:1770213729679-5
ALTER TABLE group_student_homework
    DROP CONSTRAINT fk_group_student_homework_on_group;

-- changeset salikhdev:1770213729679-6
ALTER TABLE group_student_homework
    DROP CONSTRAINT fk_group_student_homework_on_home_work;

-- changeset salikhdev:1770213729679-7
ALTER TABLE group_student_homework
    DROP CONSTRAINT fk_group_student_homework_on_student;

-- changeset salikhdev:1770213729679-1
CREATE TABLE homework_submit
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    group_id     BIGINT                                  NOT NULL,
    home_work_id BIGINT                                  NOT NULL,
    student_id   BIGINT                                  NOT NULL,
    description  VARCHAR(255),
    homework_url VARCHAR(255),
    score        BIGINT,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_homework_submit PRIMARY KEY (id)
);

-- changeset salikhdev:1770213729679-2
ALTER TABLE homework_submit
    ADD CONSTRAINT FK_HOMEWORK_SUBMIT_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset salikhdev:1770213729679-3
ALTER TABLE homework_submit
    ADD CONSTRAINT FK_HOMEWORK_SUBMIT_ON_HOME_WORK FOREIGN KEY (home_work_id) REFERENCES homework (id);

-- changeset salikhdev:1770213729679-4
ALTER TABLE homework_submit
    ADD CONSTRAINT FK_HOMEWORK_SUBMIT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES _user (id);

-- changeset salikhdev:1770213729679-8
DROP TABLE group_student_homework CASCADE;

