-- liquibase formatted sql

-- changeset xumoyuddin:1770183800867-1
CREATE TABLE _user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    role       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    avatar_url VARCHAR(255),
    birth_date date,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-2
CREATE TABLE courses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    price      DECIMAL                                 NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-3
CREATE TABLE group_homework
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    group_id     BIGINT                                  NOT NULL,
    homework_id  BIGINT                                  NOT NULL,
    creator_id   BIGINT                                  NOT NULL,
    deadline     TIMESTAMP WITHOUT TIME ZONE,
    is_submitted BOOLEAN,
    CONSTRAINT pk_group_homework PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-4
CREATE TABLE group_student_homework
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    group_id     BIGINT                                  NOT NULL,
    home_work_id BIGINT                                  NOT NULL,
    student_id   BIGINT                                  NOT NULL,
    description  VARCHAR(255),
    homework_url VARCHAR(255),
    score        BIGINT,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_student_homework PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-5
CREATE TABLE group_students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    group_id   BIGINT                                  NOT NULL,
    student_id BIGINT                                  NOT NULL,
    joined_at  date                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_students PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-6
CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    number     BIGINT                                  NOT NULL,
    capacity   BIGINT                                  NOT NULL,
    mentor_id  BIGINT,
    course_id  BIGINT,
    start_time time WITHOUT TIME ZONE NOT NULL,
    end_time   time WITHOUT TIME ZONE NOT NULL,
    start_date date                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_by BIGINT,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-7
CREATE TABLE homework
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT,
    content_url VARCHAR(255)                            NOT NULL,
    max_score   BIGINT                                  NOT NULL,
    CONSTRAINT pk_homework PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-8
CREATE TABLE resource
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    original_name VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    size          BIGINT                                  NOT NULL,
    key           VARCHAR(255)                            NOT NULL,
    url           VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    extension     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resource PRIMARY KEY (id)
);

-- changeset xumoyuddin:1770183800867-9
ALTER TABLE _user
    ADD CONSTRAINT uc__user_email UNIQUE (email);

-- changeset xumoyuddin:1770183800867-10
ALTER TABLE groups
    ADD CONSTRAINT uc_groups_number UNIQUE (number);

-- changeset xumoyuddin:1770183800867-11
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

-- changeset xumoyuddin:1770183800867-12
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_CREATED_BY FOREIGN KEY (created_by) REFERENCES _user (id);

-- changeset xumoyuddin:1770183800867-13
ALTER TABLE group_homework
    ADD CONSTRAINT FK_GROUP_HOMEWORK_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES _user (id);

-- changeset xumoyuddin:1770183800867-14
ALTER TABLE group_homework
    ADD CONSTRAINT FK_GROUP_HOMEWORK_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset xumoyuddin:1770183800867-15
ALTER TABLE group_homework
    ADD CONSTRAINT FK_GROUP_HOMEWORK_ON_HOMEWORK FOREIGN KEY (homework_id) REFERENCES homework (id);

-- changeset xumoyuddin:1770183800867-16
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_MENTOR FOREIGN KEY (mentor_id) REFERENCES _user (id);

-- changeset xumoyuddin:1770183800867-17
ALTER TABLE group_students
    ADD CONSTRAINT FK_GROUP_STUDENTS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset xumoyuddin:1770183800867-18
ALTER TABLE group_students
    ADD CONSTRAINT FK_GROUP_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES _user (id);

-- changeset xumoyuddin:1770183800867-19
ALTER TABLE group_student_homework
    ADD CONSTRAINT FK_GROUP_STUDENT_HOMEWORK_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset xumoyuddin:1770183800867-20
ALTER TABLE group_student_homework
    ADD CONSTRAINT FK_GROUP_STUDENT_HOMEWORK_ON_HOME_WORK FOREIGN KEY (home_work_id) REFERENCES homework (id);

-- changeset xumoyuddin:1770183800867-21
ALTER TABLE group_student_homework
    ADD CONSTRAINT FK_GROUP_STUDENT_HOMEWORK_ON_STUDENT FOREIGN KEY (student_id) REFERENCES _user (id);

